### PR TITLE
Several fixes and new api features

### PR DESCRIPTION
**Pull request by DArkHekRoMaNT**
- Fixed api/mod response releaseid as string (int now)
- Fixed api/mods response "asset/\<assetid\>/" if logo not exists (null now)
- Fixed api/mods response array with one empty string if modidstrs not exists (empty array now)
- Added api/authors, api/comments and api/changelogs
- Added urlalias and type to api/mod/modid response (previously only shown in api/mods)
- Added mods filter by author (userid)
- Updated readme file to show API changes

### CODE REVIEW

**Comment by DArkHekRoMaNT** [comment]
I made global changelogs and comments so far, this can be manually linked by assetid. I can add them to api/mod/[modid] but that would make it even bigger.

Perhaps it makes sense to move part of the answer to api/mod/[modid]/smth? Or api/smth/[modid]? For example, it's completely redundant to get a complete mod from moddb with releases, changelog, text, and comments if you're just checking it's lastmodified. You can do it via api/mods, but then you will get all the mods.

**Comment by tyronx** [comment]
yea, would make sense to put that stuff seperatly

**Comment by tyronx** [comment]
thanks for the PR!

**Comment by tyronx** [comment]
ohwait, before i put this online - the comments and changelogs need to have a required modid arg. It doesn't make much sense to list *all* comments/changelogs, imo. 

And if someone really wants that, it needs to limited to the newest 100 or so. This would generate too much load/traffic otherwise.

**Pull request merged**
